name: pan_de_vida
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2+2

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.4.0
  cached_network_image: ^3.3.1
  calendar_date_picker2: ^1.1.7
  calendar_view: ^1.4.0
  delayed_display: ^2.0.0
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  get: ^4.6.6
  get_cli: ^1.9.1
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  group_button: ^5.3.4
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.20.2
  material_symbols_icons: ^4.2815.0
  mobile_scanner: ^6.0.2
  permission_handler: ^11.4.0
  solar_icons: ^0.0.5
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  wheel_picker: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tests_ministerio/
    - .env
