name: pan_de_vida
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.2
  get: ^4.6.6
  get_cli: ^1.8.1
  get_storage: ^2.1.1
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  solar_icons: ^0.0.5
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
