name: pan_de_vida
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  calendar_date_picker2: ^1.1.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  # flutter_localization: ^0.2.3
  flutter_localizations:
    sdk: flutter
  flutter_phone_direct_caller: ^2.1.1
  geolocator: ^13.0.2
  get: ^4.6.6
  get_cli: ^1.9.1
  get_storage: ^2.1.1
  google_maps_flutter: ^2.9.0
  group_button: ^5.3.4
  http: ^1.2.2

  intl: ^0.19.0

  mobile_scanner: ^6.0.2

  solar_icons: ^0.0.5
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  wheel_picker: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
